name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout git repo
    - name: Checkout
      uses: actions/checkout@master
    # Install node js
    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    # deploy to github pages
    - name: vuepress-deploy
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_REPO: github.com/elrictang/elrictang.github.io
      run: |
        npm install
        npm run build
        cd docs/.vuepress/dist
        git init
        git config --global user.email "1032705963@qq.com"
        git config --global user.name "tangjianfeng"
        git add -A
        git commit -m "deploy"
        git push -f "https://$GITHUB_TOKEN@$GITHUB_REPO" master:master

      