name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout git repo
    - name: Checkout
      uses: actions/checkout@master
    # Install node js
    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    # deploy to github pages
    - name: vuepress-deploy
      run: ./deploy.sh

      